world:
  unload-spawn-chunk: true
  disable-unload-spawn-chunk:
    - 'exampleWorld1'
    - 'exampleWorld2'
  chunks-per-ambient-spawn-limit:
    enable: true
    global: -1
    per-world:
      exampleworld1: 8
      exampleworld2: 8
  chunks-per-animal-spawn-limit:
    enable: true
    global: -1
    per-world:
      exampleworld1: 64
      exampleworld2: 64
  chunks-per-monster-spawn-limit:
    enable: true
    global: -1
    per-world:
      exampleworld1: 64
      exampleworld2: 64
  chunks-per-water-ambient-spawn-limit:
    enable: true
    global: -1
    per-world:
      exampleworld1: 8
      exampleworld2: 8
  chunks-per-water-animal-spawn-limit:
    enable: true
    global: -1
    per-world:
      exampleworld1: 8
      exampleworld2: 8
  ticks-per-ambient-spawn:
    enable: true
    global: 1
    per-world:
      exampleworld1: 1
      exampleworld2: 1
  ticks-per-animal-spawn:
    enable: true
    global: 400
    per-world:
      exampleworld1: 400
      exampleworld2: 400
  ticks-per-monster-spawn:
    enable: true
    global: 1
    per-world:
      exampleworld1: 1
      exampleworld2: 1
  ticks-per-water-ambient-spawn:
    enable: true
    global: 1
    per-world:
      exampleworld1: 1
      exampleworld2: 1
  ticks-per-water-animal-spawn:
    enable: true
    global: 1
    per-world:
      exampleworld1: 1
      exampleworld2: 1